# Generated by Django 5.0.7 on 2024-07-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_cuisinetype_name_ingredient_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='featured_image',
        ),
    ]
